export { default as AddComment } from './AddComment.vue'
export { default as CommentItem } from './CommentItem.vue'
export { default as VideoDuration } from './VideoDuration.vue'
export { default as VideoItem } from './VideoItem.vue'
export { default as VideosGrid } from './VideosGrid.vue'
export { default as VideoThumbnail } from './VideoThumbnail.vue'
