FROM node:24.11.1-alpine3.23

RUN apk add --no-cache ffmpeg

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci

COPY . .

ARG APP_NAME
RUN npm run build ${APP_NAME}

EXPOSE 3000
CMD ["node", "dist/apps/${APP_NAME}/main"]
