name: video-platform

networks:
  video-network:
    driver: bridge

services:
  video-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: video-api
    command: npm run start:dev -- video-api
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - ./apps/video-api/src:/app/apps/video-api/src
      - ./libs:/app/libs

  video-upload:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: video-upload
    command: npm run start:dev -- video-upload
    ports:
      - 3001:3000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - ./apps/video-upload/src:/app/apps/video-upload/src
      - ./libs:/app/libs

  video-cdn:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: video-cdn
    command: npm run start:dev -- video-cdn
    ports:
      - 3002:3000
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - ./apps/video-cdn/src:/app/apps/video-cdn/src
      - ./libs:/app/libs

  video-processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
      args:
        APP_NAME: video-processor
    command: npm run start:dev -- video-processor
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      minio:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - video-network
    volumes:
      - ./apps/video-processor/src:/app/apps/video-processor/src
      - ./libs:/app/libs

  postgres:
    image: postgres:17.7
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    shm_size: 128mb
    networks:
      - video-network
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB}', '-U', '${POSTGRES_USER}']
      interval: 1s
      timeout: 2s
      retries: 10

  valkey:
    image: valkey/valkey:8.1.5
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - video-network
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 1s
      timeout: 2s
      retries: 10

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    ports:
      - ${MINIO_PORT}:9000   # S3 API
      - 9001:9001   # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ':9001'
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      - video-network
    volumes:
      - ./volumes/minio_data:/data

  rabbitmq:
    # image: rabbitmq:4.2.1-management
    image: rabbitmq:4.2.1
    ports:
      - ${RABBITMQ_PORT}:5672     # MQ API
      - 15672:15672   # Web console
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - video-network
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 1s
      timeout: 2s
      retries: 10

  meilisearch:
    image: getmeili/meilisearch:v1.30.0
    ports:
      - ${MEILISEARCH_PORT}:7700
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    networks:
      - video-network
    volumes:
      - ./volumes/meili_data:/meili_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${MEILISEARCH_PORT}/health']
      interval: 1s
      timeout: 2s
      retries: 10
