name: video-platform-test

networks:
  video-network:
    driver: bridge

services:
  postgres:
    image: postgres:17.7
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    shm_size: 128mb
    networks:
      - video-network
    volumes:
      - /tmp/volumes/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD', 'pg_isready', '-d', '${POSTGRES_DB}', '-U', '${POSTGRES_USER}']
      interval: 1s
      timeout: 2s
      retries: 10

  valkey:
    image: valkey/valkey:8.1.5
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - video-network
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 1s
      timeout: 2s
      retries: 10

  minio:
    image: quay.io/minio/minio:latest
    ports:
      - ${MINIO_PORT}:9000   # S3 API
      - 9011:9001   # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ':9001'
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      - video-network

  rabbitmq:
    # image: rabbitmq:4.2.1-management
    image: rabbitmq:4.2.1
    ports:
      - ${RABBITMQ_PORT}:5672     # MQ API
      - 15682:15672   # Web console
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - video-network
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 1s
      timeout: 2s
      retries: 10

  meilisearch:
    image: getmeili/meilisearch:v1.30.0
    ports:
      - ${MEILISEARCH_PORT}:7700
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    networks:
      - video-network
    volumes:
      - /tmp/volumes/meili_data:/meili_data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${MEILISEARCH_PORT}/health']
      interval: 1s
      timeout: 2s
      retries: 10
