// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from 'dotenv';
import expand from 'dotenv-expand';
import { defineConfig, env } from 'prisma/config';

expand.expand(dotenv.config());

export default defineConfig({
  schema: 'libs/video-lib/src/database/prisma/schema',
  migrations: {
    path: 'libs/video-lib/src/database/prisma/migrations',
  },
  datasource: {
    url: env('POSTGRES_URL_LOCAL'),
  },
});
