name: Test server on push

on:
  push:
    branches:
      - '**'
    paths: 
       - 'video-server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'

      - name: Install dependencies
        working-directory: ./video-server
        run: npm install

      - name: Generate client
        working-directory: ./video-server
        run: npx prisma generate
  
      - name: Lint
        working-directory: ./video-server
        run: npm run lint

      - name: Run video-lib unit tests
        working-directory: ./video-server
        run: npm run test:lib

      - name: Run video-api E2E tests
        working-directory: ./video-server
        run: export NODE_OPTIONS="--max_old_space_size=4096" && npm run test:api:e2e

      - name: Run video-upload E2E tests
        working-directory: ./video-server
        run: export NODE_OPTIONS="--max_old_space_size=4096" && npm run test:upload:e2e
